#! /usr/bin/python
#
# grep-merges - search for pending merges from Debian
#
# Copyright (C) 2010 Canonical Ltd.
# Authors:
#  - Colin Watson <cjwatson@ubuntu.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import optparse
import sys
import json

from httplib2 import Http, HttpLib2Error

import ubuntutools.misc


def main():
    parser = optparse.OptionParser(usage='%prog [options] [string]',
            description='List pending merges from Debian matching string')
    args = parser.parse_args()[1]

    if len(args) > 1:
        parser.error('Too many arguments')
    elif len(args) == 1:
        match = args[0]
    else:
        match = None

    ubuntutools.misc.require_utf8()

    for component in ('main', 'main-manual',
                      'restricted', 'restricted-manual',
                      'universe', 'universe-manual',
                      'multiverse', 'multiverse-manual'):

        url = 'https://merges.ubuntu.com/%s.json' % component
        try:
            headers, page = Http().request(url)
        except HttpLib2Error, e:
            print >> sys.stderr, str(e)
            sys.exit(1)
        if headers.status != 200:
            print >> sys.stderr, "%s: %s %s" % (url, headers.status,
                                                headers.reason)
            sys.exit(1)

        for merge in json.loads(page):
            package = merge['source_package']
            author, uploader = '', ''
            if merge.get('user'):
                author = merge['user']
            if merge.get('uploader'):
                uploader = '(%s)' % merge['uploader']
            pretty_uploader = ' '.join((author, uploader)).strip()
            if (match is None or
                match in package or match in author or match in uploader):
                print '%s\t%s' % (package.encode("utf-8"), pretty_uploader.encode("utf-8"))

if __name__ == '__main__':
    main()
