#!/bin/sh
#
# Copyright (C) Jamin W. Collins <jcollins@asgardsrealm.net>
# Copyright (C) Jordan Mantha <mantha@ubuntu.com>
#
# ##################################################################
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# See file /usr/share/common-licenses/GPL for more details.
#
# ##################################################################
#
# This script is a wrapper to be able to easily use pbuilder for
# different Ubuntu distributions (eg, Lucid, Natty, etc).
#
# Create symlinks to this script naming them 'pbuilder-lucid',
# 'pbuilder-natty', etc. If you want additional features try out the more
# advanced script 'pbuilder-dist'.

OPERATION=$1
DISTRIBUTION=`basename $0 | cut -f2 -d '-'`
PROCEED=false
BASE_DIR="$HOME/pbuilder"

usage() {
    prog=$(basename $0)
    cat <<EOF
Usage: $prog command [pbuilder-options...]

A simple multi-release pbuilder wrapper

Valid commands are:
    create
    update
    build
    clean
    login
    execute

Options:
  -h, --help  show this help message and exit
EOF
   exit $1
}

case $OPERATION in
    create|update|build|clean|login|execute)
        ;;
    -h|--help)
        usage 0
        ;;
    *)
        usage 1
        ;;
esac
shift
if [ ! -d $BASE_DIR/${DISTRIBUTION}_result ]; then
    mkdir -p $BASE_DIR/${DISTRIBUTION}_result/
fi
sudo pbuilder $OPERATION \
  --basetgz $BASE_DIR/$DISTRIBUTION-base.tgz \
  --distribution $DISTRIBUTION \
  --buildresult $BASE_DIR/$DISTRIBUTION_result \
  --othermirror "deb http://archive.ubuntu.com/ubuntu $DISTRIBUTION universe multiverse" "$@"
