#!/bin/bash
# Copyright (C) 2007 Siegfried-A. Gevatter <rainct@ubuntu.com>
# Based upon a short script by an unknown author
# License: GPLv2+
#
# This script is used to find the reverse build dependencies
# that a package has.

usage() {
	echo "Usage: $0 [-c|-s] <package name>"
	echo "Options:"
	echo " -c: Print only the number of reverse dependencies."
	echo " -s: Print all reverse dependencies in a single line."
}

if [ "$1" = '-c' ]
then
	count=1
	shift
fi

if [ "$1" = '-s' ]
then
	single_line=1
	shift
fi

if [ $# -ne 1 ];
then
	usage
	exit 1
fi

if [ "$1" = '-h' ] || [ "$1" = '--help' ]
then
	usage
	exit 0
fi

result=$(
	grep-dctrl -sPackage -F Build-Depends,Build-Depends-Indep $1 \
	/var/lib/apt/lists/*Sources | cut -d ' ' -f 2)

if [ -z $count ] && [ -z $single_line ]
then
	echo "$result"
else
	if [ -z $count ]
	then
		echo $result
	else 
		echo "$result" | wc -l
	fi
fi
