#!/bin/bash
set -e

# Get the latest CD snapshot release.
Distro="$1"
if [ -z "$Distro" ]; then
	echo "Which distro?" >&2
	exit 1
fi
Release="$2"
if [ -z "$Release" ]; then
	echo "Which ISO release?" >&2
	exit 1
fi
Ver=gutsy
Code=tribe

cd ~/distros/ubuntu/"${Distro}"/"${Ver}"
mkdir -p "${Code}"-"${Release}"
cd "${Code}"-"${Release}"

cp ../*.iso . || true

if [ "${Distro}" == "ubuntu" ]; then
	Origin="releases"
	Flavors="alternate desktop server"
	Archs="i386"
	#Archs="i386 amd64 powerpc"
elif [ "${Distro}" == "edubuntu" ]; then
	Origin="${Distro}/releases"
	Flavors="desktop server serveraddon"
	Archs="i386"
	#Archs="i386 amd64"
elif [ "${Distro}" == "ubuntu-server" ]; then
	Origin="releases"
	Flavors="server"
	Archs="i386"
	#Archs="i386 amd64"
else
	Origin="${Distro}/releases"
	Flavors="alternate desktop"
	Archs="i386"
	#Archs="i386 amd64"
fi

for arch in $Archs; do
	for flavor in $Flavors; do
		rsync "rsync://cdimage.ubuntu.com/cdimage/${Origin}/${Ver}/${Code}-${Release}/${Ver}-${flavor}-${arch}.iso" "${Ver}-${flavor}-${arch}.iso"
	done
done
