.\" Copyright (c) 2009-2011, Benjamin Drung <bdrung@ubuntu.com>
.\"
.\" Permission to use, copy, modify, and/or distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.TH DISTRO-INFO "1" "January 2011" "ubuntu-dev-tools"
.SH NAME
distro-info \- provides information about the distributions' releases
.SH SYNOPSIS
.B distro-info
[\fIOPTIONS\fR]
.SH DESCRIPTION
.B distro-info
is a symlink to the distro-info command of your distribution.
On Debian it links to
.B debian-distro-info
and on Ubuntu it links to
.B ubuntu-distro-info.
All options, which are described in this manual page, are available in all
.B distro-info
commands. All other options, which are not described here, are distribution
specific.
.SH OPTIONS
.TP
\fB\-\-date\fR=\fIDATE
date for calculating the version (default: today)
.TP
\fB\-h\fR, \fB\-\-help\fR
display help message and exit
.TP
\fB\-a\fR, \fB\-\-all\fR
list all known versions
.TP
\fB\-d\fR, \fB\-\-devel\fR
latest development version
.TP
\fB\-s\fR, \fB\-\-stable\fR
latest stable version
.TP
\fB\-\-supported\fR
list of all supported stable versions
.TP
\fB\-\-unsupported\fR
list of all unsupported stable versions
.SH SEE ALSO
.BR debian-distro-info (1),
.BR ubuntu-distro-info (1)
.SH AUTHOR
The script and this manual page was written by
Benjamin Drung <bdrung@ubuntu.com>.
