.TH grab\-merge 1 "March 26, 2009" "ubuntu-dev-tools"

.SH NAME
grab\-merge \- grabs a merge's files from merges.ubuntu.com.

.SH SYNOPSIS
\fBgrab\-merge\fP <\fIpackage name\fP>

.SH DESCRIPTION
\fBgrab\-merge\fP is a script that downloads a merge's packaging files and report
from merges.ubuntu.com. Placing them in a new directory for working from.

.SH AUTHORS
\fBgrab\-merge\fP was written by Scott James Remnant <scott@ubuntu.com> and
this manpage by Jonathan Davies <jpds@ubuntu.com>.
.PP
Both are released under the GNU General Public License, version 2 or
later.
