.TH GRAB\-ATTACHMENTS "1" "10 August 2008" "ubuntu-dev-tools"
.SH NAME
grab\-attachments \- downloads attachments from a Launchpad bug
.SH SYNOPSIS
.B grab\-attachments\fR <\fIbug-number\fR>
.br
.B grab\-attachments \-h
.SH DESCRIPTION
\fBgrab\-attachments\fR is a script to download all attachments from a
Launchpad bug report into the current directory.

.SH OPTIONS
Listed below are the command line options for grab\-attachments:
.TP
.B \-h
Display a help message and exit.
.TP
.B <bug-number>
Specifies the Launchpad bug number that the script should download
attachments from.

.SH AUTHOR
\fBgrab\-attachments\fR was written by Daniel Holbach and this manual page
was written by Jonathan Patrick Davies.
.PP
Both are released under the GNU General Public License, version 2.
