.TH harvest 1 "March 21, 2011" "ubuntu-dev-tools"

.SH NAME
harvest \- grabs information about a given source package from harvest.ubuntu.com.

.SH SYNOPSIS
\fBharvest\fP <\fIsource package name\fP>

.SH DESCRIPTION
\fBharvest\fP is a script that downloads information about development 
opportunities from harvest.ubuntu.com and gives a summary of the types of
opportunities.

.SH AUTHORS
\fBharvest\fP and its manpage were written by Daniel Holbach 
<daniel.holbach@ubuntu.com>.
.PP
Both are released under the GNU General Public License, version 3 or
later.
