.TH HUGDAYLIST "1" "August 27, 2008" "ubuntu-dev-tools"

.SH NAME
hugdaylist \- produce MoinMoin wiki formatted tables based on a Launchpad bug
list

.SH SYNOPSIS
.B hugdaylist [\fB\-n <NUMBER>, \fB\-\-number=<NUMBER>\fP]
\fBlaunchpad-buglist-url\fP

.SH DESCRIPTION
\fBhugdaylist\fP produces MoinMoin wiki formatted tables based on a
Launchpad bug list

.SH OPTIONS
.TP
\fB\-\-number=<NUMBER>\fP
This option allows you to specify the number of entries to output.
.TP
\fBlaunchpad-buglist-url\fP
Required, this option is a URL pointing to a launchpad bug list.


.SH AUTHOR
\fBhugdaylist\fP has been written by Canonical Ltd., Daniel Holbach
<daniel.holbach@canonical.com> and Jonathan Patrick Davies <jpds@ubuntu.com>.
This manual page was written by Ryan Kavanagh <ryanakca@kubuntu.org>.
.PP
Both are released under the GNU General Public License, version 3.
