.TH lp-project-upload "1" "05 September 2009" "ubuntu-dev-tools"
.SH NAME
lp\-project\-upload \- Upload a release tarball to a Launchpad project.

.SH SYNOPSIS
.B lp\-project\-upload
.I <project name> <version> <tarball> [new milestone] [changelog file] [releasenotes file]

.SH DESCRIPTION
\fBlp\-project\-upload\fR uploads a tarball release of a project to Launchpad.
It can create milestones and releases on the fly after confirmation.

If there is a file \fItarball\fB.asc\fR, it is uploaded as the signature of the
tarball.

You can optionally provide the name of the next milestone, which will be created if specified.

You can optionally provide filename(s) specifying the changelog and release notes entries for this release.  Note that these might be /dev/null, if you do not want to provide changelog or release notes information.  If these are not specified, an interactive editor will allow you to compose these.

.SH AUTHORS
\fBlp\-project\-upload\fR was written by Martin Pitt <martin.pitt@ubuntu.com> and enhanced by Dustin Kirkland <kirkland@ubuntu.com>.
.PP
It is released under the terms of the GNU General Public License, version 2
or (at your option) any later version.
