.TH lp\-set\-dup "1" "March 6 2010" "ubuntu-dev-tools"
.SH NAME
lp\-set-\dup \- mark one or more bugs as duplicate of another bug

.SH SYNOPSIS
.B lp\-set\-dup [\-f] <main bug> <duplicate bug> [<duplicate bug> ...]
.br
.B lp\-set\-dup \-\-help

.SH DESCRIPTION
\fBlp\-set\-dup\fR allow to easily mark one or more bug as duplicate of
another bug. It checks for permission to operate on a given bug first,
then perform required tasks on Launchpad.

.SH OPTIONS
Listed below are the command line options for \fBlp\-set\-dup\fR:
.TP
.B \-h or \-\-help
Display a help message and exit.
.TP
.B \-f
Skip confirmation prompt.

.SH AUTHORS
\fBlp\-set\-dup\fR was written by Loïc Minier <lool@dooz.org>,
and this manual page was written by Luca Falavigna <dktrkranz@debian.org>.
.PP
Both are released under the terms of the GNU General Public License, version 2.
