.TH lp-shell "1" "13 January 2010" "ubuntu-dev-tools"
.SH NAME
lp\-shell \- Open an interactive launchpadlib shell.

.SH SYNOPSIS
.B lp\-shell
[service]

.SH DESCRIPTION
.B lp\-shell
opens an interactive Python shell with a launchpadlib.Launchpad object "lp"
which is ready for use.

It authenticates against Launchpad with the consumer name "test".

It uses by default the "edge" Launchpad service and the default API version.
If you want to connect to an other Launchpad service, call
.B lp\-shell
with the service name as the second argument. lp-shell supports all services
known by launchpadlib Python module.
Currently known are (list can be incomplete or outdated): "production", "edge",
"staging", "dogfood".

.SH AUTHORS
.B lp\-shell
was written by Martin Pitt <martin.pitt@ubuntu.com>.
.PP
It is released under the terms of the GNU General Public License, version 2
or (at your option) any later version.
