.TH MK\-SBUILD "1" "09 February 2010" "ubuntu-dev-tools"

.SH NAME
mk\-sbuild \- creates chroots via schroot and sbuild

.SH SYNOPSIS
\fBmk\-sbuild\fR [\fB\-\-arch=ARCH\fR] [\fB\-\-name=NAME\fR]
[\fB\-\-personality=PERSONALITY\fR] [\fB\-\-debug\fR] [\fB\-\-source\-template=FILE\fR]
[\fB\-\-debootstrap\-mirror=URL\fR] <\fBRelease\fR>

.SH DESCRIPTION
\fBmk\-sbuild\fR creates chroots via schroot and sbuild.

.SH OPTIONS
Listed below are the command line options for mk\-sbuild:
.TP
.B \-\-arch=ARCH
What architecture to select (defaults to the native architecture).
.TP
.B \-\-name=NAME
Base name for the schroot (arch is appended).
.TP
.B \-\-personality=PERSONALITY
What personality to use (defaults to match \-\-arch).
.TP
.B \-\-debug
Turn on script debugging.
.TP
.B \-\-skip\-updates
Do not include the \-updates pocket in the installed sources.list.
.TP
.B \-\-source\-template=FILE
Use FILE as the sources.list template (defaults to $HOME/.mk\-sbuild.sources).
.TP
.B \-\-debootstrap\-mirror=URL
Use URL as the debootstrap source (defaults to http://ports.ubuntu.com for lpia,
official Ubuntu repositories for the supported architectures).
.TP
.B \-\-distro
Enable distro-specific logic.  Currently known distros: "ubuntu" (default)
and "debian".
.TP
.B \-\-vg
Specify a volume group, and subsequently use SCHROOT_TYPE of "lvm-snapshot"
rather than "directory" (via aufs) mounts.

.SH ENVIRONMENT VARIABLES
.TP
.B LV_SIZE
Size of source LVs (defaults to 5G).
.TP
.B SNAPSHOT_SIZE
Size of snapshot LVs (defaults to 4G).
.TP
.B SCHROOT_CONF_SUFFIX
Lines to append to schroot entries.
.TP
.B SKIP_UPDATES
Do not include the \-updates pocket in the installed sources.list.
.TP
.B SOURCE_CHROOTS_DIR
use SOURCE_CHROOTS_DIR as home of schroot source directories. (default
/var/lib/schroot/chroots)

.SH FILES
.TP
.B $HOME/.mk\-sbuild.rc
Sourced for environment variables (defined above).
.TP
.B $HOME/.mk\-sbuild.sources[.$DISTRO]
Can contain a customized sources.list.
It will be read when creating the schroot.
If a file with ".ubuntu" or ".debian" is found (based on the \-\-distro
argument) that file will use used instead.
See sources.list(5) for more details on the format.
.TP
.B $HOME/.mk\-sbuild.schroot.conf[.$SCHROOT_TYPE]
Can contain a customized configuration section to be inserted into
/etc/schroot/schroot.conf.
If a file with ".lvm-snapshot" or ".directory" is found (based on the presence
of the \-\-vg argument) that file will use used instead.
See schroot.conf(5) for more details on the format.
.SH USING THE CHROOTS
.TP
To CHANGE the golden image: \fBsudo schroot \-c ${CHROOT_NAME}\-source \-u root\fR
.TP
To ENTER an image snapshot: \fBschroot \-c ${CHROOT_NAME}\fR
.TP
To BUILD within a snapshot: \fBsbuild \-d ${SCHROOT_NAME} PACKAGE*.dsc\fR
.TP
for example, to update the packages in a golden image: \fBschroot \-c ${CHROOT_NAME}\-source \-u root -- sh \-c "apt-get \-qq update && apt-get \-qy upgrade && apt-get clean" </dev/null\fR

.SH SEE ALSO
sbuild\-setup (7), sources.list (5), schroot.conf (5),
https://help.ubuntu.com/community/SbuildLVMHowto

.SH AUTHOR
\fBmk\-sbuild\fR was written by Kees Cook <kees@ubuntu.com>.
This man page was written by Ryan Kavanagh <ryanakca@kubuntu.org>.
Both are released under the GNU General Public License, version 3 or later.
