.TH PULL\-LP\-SOURCE "1" "4 August 2008" "ubuntu-dev-tools"

.SH NAME
pull\-lp\-source \- download a source package from Launchpad

.SH SYNOPSIS
.B pull\-lp\-source \fR[\fB\-h\fR]\fB <\fBsource package\fR> [\fItarget release\fR]

.SH DESCRIPTION
\fBpull\-lp\-source\fR downloads and extracts the latest version of
<\fBsource package\fR> from Launchpad.
If the optional parameter [\fItarget release\fR] is specified, the latest
version in that release will be downloaded instead.

.SH OPTIONS
Listed below are the command line options for pull\-lp\-source:
.TP
.B \-h, \-\-help
Display a help message and exit.
.TP
.B <source package>
This is the source package that you would like to be downloaded from Launchpad.
.TP
.B [target release]
This is the release that you would like the source package to be downloaded from.
This value defaults to the current development release.

.SH ENVIRONMENT VARIABLES
.TP
DIST
Specifies the default target.

.SH AUTHOR
.PP
\fBpull\-lp\-source\fR and this manual page were written by Iain Lane
<iain@orangesquash.org.uk>.
Both are released under the GNU General Public License, version 3 or later.
