.TH PULL-DEBIAN-DEBDIFF "1" "June 2010" "ubuntu-dev-tools"
.SH NAME
\fBpull-debian-debdiff\fR \- find, download, and generate a debdiff

.SH SYNOPSIS
\fBpull-debian-debdiff\fR <package> <version>

.SH DESCRIPTION
\fBpull-debian-debdiff\fR attempts to find and download a specific version of a Debian package and its immediate parent to generate a debdiff.

.SH AUTHORS
\fBpull-debian-debdiff\fR was written by Kees Cook <kees@ubuntu.com>.

This manual page was written by Andrew Starr-Bochicchio <a.starr.b@gmail.com>.
.PP
Both are released under the terms of the GNU General Public License, version 3, or (at your option) any later version.
