.TH PULL\-DEBIAN\-SOURCE "1" "20 December 2008" "ubuntu-dev-tools"

.SH NAME
pull\-debian\-source \- download a source package from Debian

.SH SYNOPSIS
.B pull\-debian\-source \fR[\fIoptions\fR] <\fIsource package\fR> [\fItarget release\fR]

.SH DESCRIPTION
\fBpull\-debian\-source\fR downloads and extracts the latest version of
<\fBsource package\fR> from Debian.
If the optional parameter [\fItarget release\fR] is specified, the latest
version in that release will be downloaded instead.

.SH OPTIONS
Listed below are the command line options for pull\-debian\-source:
.TP
.I source package
This is the source package that you would like to be downloaded from Debian.
.TP
.I target release
This is the release that you would like the source package to be downloaded from.
This value defaults to 'unstable'.
.TP
.BR \-h ", " \-\-help
Display the usage instructions and exit.
.TP
.B \-m \fIDEBMIRROR\fR, \fB\-\-mirror\fR=\fIDEBMIRROR\fR
Use the specified mirror.
Should be in the form \fBhttp://ftp.debian.org/debian\fR.
If the package isn't found on this mirror, \fBpull\-debian\-source\fR
will fall back to the default mirror.
.TP
.BR \-n ", " \-\-no\-fallback
If specified, \fBpull\-debian\-source\fR won't fall back to the default
mirror, should it encounter an error.
.TP
.B \-\-no\-conf
Do not read any configuration files, or configuration from environment
variables.

.SH ENVIRONMENT
All of the \fBCONFIGURATION VARIABLES\fR below are also supported as
environment variables.
Variables in the environment take precedence to those in configuration
files.

.SH CONFIGURATION VARIABLES
The following variables can be set in the environment or in
.BR ubuntu\-dev\-tools (5)
configuration files.
In each case, the script\-specific variable takes precedence over the
package\-wide variable.
.TP
.BR PULL_DEBIAN_SOURCE_DEBMIRROR ", " UBUNTUTOOLS_DEBMIRROR
The default value for \fB\-\-mirror\fR.
.TP
.BR PULL_DEBIAN_SOURCE_MIRROR_FALLBACK ", " UBUNTUTOOLS_MIRROR_FALLBACK
The default value for \fB\-\-no\-fallback\fR.

.SH SEE ALSO
.BR ubuntu\-dev\-tools (5)

.SH AUTHOR
.PP
\fBpull\-debian\-source\fR and this manual page were written by Nathan Handler
<nhandler@ubuntu.com>. The manual page was based on Iain Lane's manual page for
pull-lp-source.
Both are released under the GNU General Public License, version 3 or later.
