.TH REQUESTSYNC "1" "19 January 2008" "ubuntu-dev-tools"
.SH NAME
requestsync \- helper to file sync requests for Ubuntu
.SH SYNOPSIS
.B requestsync\fR [\fB\-ns\fR] [\fB\-k \fIkeyid\fR] <\fBsource package\fR> <\fBtarget release\fR> [\fIbase version\fR]

.B requestsync \-\-lp\fR [\fB\-ns\fR] <\fBsource package\fR> <\fBtarget release\fR> [\fIbase version\fR]

.B requestsync \-h
.SH DESCRIPTION
.PP 
\fBrequestsync\fR looks at the versions of <source package> in Debian and
Ubuntu and prompts for an explanation of why the Ubuntu changes (if there
are any) should be dropped.
The changelog entry is then downloaded from packages.debian.org. If the sync
request is being filed per email (default), a prompt for your GPG passphrase
follows so that it can sign the mail and send it off to Launchpad.
Alternatively a sync request can be filed directly using the launchpadbugs
python module (option \fB\-\-lp\fR). \fBrequestsync\fR falls back to mail
the sync request if submitting using the launchpadbugs module fails.
.SH OPTIONS
.PP
Listed below are the command line options for requestsync:
.TP
.B \-h
Display a help message and exit.
.TP
.B \-n
Specifies that the package is a new package, and requestsync should not
attempt to look it up in Ubuntu since it will not exist.
.TP
.B \-k \fI<keyid>\fR
Specifies your GPG key.
Can also be set with the line `\fIexport GPGKEY=<keyid>\fR' in your shell's
configuration (For example: \fI$HOME/.bashrc\fR).
This is only used if the sync request is mailed to Launchpad.
.TP
.B \-\-lp
Use the launchpadbugs python module (packaged as python-launchpad-bugs) to
file the sync request in Launchpad.
.TP
.B <source package>
This is the source package that you would like to be synced from Debian.
.TP
.B <target release>
This is the release that you would like the source package to be synced
into.
This should always be the latest development release of Ubuntu.
.TP
.B [base version]
In some cases, the base version (where the Ubuntu package started differing
from the Debian package) cannot be automatically determined.
Specify this option in this case.

.SH ENVIRONMENT VARIABLES
.PP
\fBrequestsync\fR uses the following variables which should be set in your
shell's configuration by adding \fIexport VARIABLE=\fR lines, where VARIABLE is
one of the following:

.TP
.B GPGKEY
Specifies your GnuPG key ID.
.TP
.B DEBEMAIL
Specifies which email should be used when sending to Launchpad.
.TP
.B DEBSMTP
Set which SMTP server to use when sending mail. If unspecified this defaults to
fioldland.ubuntu.com.
.TP
.B DEBSMTP_PORT
Sets which port of the SMTP server to use. Default is 25.
.TP
.B DEBSMTP_USER and DEBSMTP_PASS
Sets the username and password to use when authenticating to the SMTP server.

.SH SEE ALSO 
.PP 
.BR rmadison (1)

.SH AUTHOR
.PP
.B requestsync
and this manual page were written by the Ubuntu MOTU Team.
.PP
Both are released under the GNU General Public License, version 2.
