.TH REVERSE-BUILD-DEPENDS "1" "June 2012" "ubuntu-dev-tools"
.SH NAME
reverse-build-depends \- find packages that depend on a specific package to
build (reverse build depends)
.SH SYNOPSIS
.TP
.B reverse-build-depends \fR[\fIoptions\fR] \fIpackage
.SH DESCRIPTION
\fBreverse-build-depends\fR has been replaced by \fBreverse-depends \-b\fR.
This script now wraps \fBreverse-depends\fR.
Please use it in the future.
.SH SEE ALSO
.BR reverse-depends (1)
