.TH REVERSE\-BUILD\-DEPENDS 1 "January 17, 2008" "ubuntu-dev-tools"

.SH NAME
reverse\-build\-depends \- find a package's reverse build dependencies

.SH SYNOPSIS
\fBreverse\-build\-depends\fP [\fB\-c\fP|\fB\-s\fP] <\fIpackage name\fR>

.SH DESCRIPTION
\fBreverse\-build\-depends\fP is a little script that prints a list of
all those Debian package that have a build dependency upon the package
you indicate, that is, they search for its reverse build dependencies.

.SH OPTIONS
.TP
\fB\-c\fP
This option will disable normal output and print only the number of
reverse dependencies instead.
.TP
\fB\-s\fP
If you prefer to see all build dependencies in a single line, use this
option. Otherwise, each one will be printed on its own line.

.SH KNOWN BUGS AND LIMITATIONS
Note that to use \fBreverse\-build\-depends\fP it is required for the source
repositories (deb-src lines) to be enabled in your sources.list.

.SH SEE ALSO
\fBgrep\-dctrl\fR, \fBapt\-cache\fR

.SH AUTHORS
\fBreverse\-build\-depends\fP and this manual page were written by
Siegfried-Angel Gevatter Pujals <rainct@ubuntu.com> for YOU. Both are
released under the terms of the GNU General Public License (version 2
or later).
