.TH SUSPICIOUS\-SOURCE 1 "September 14, 2007" "ubuntu-dev-tools"

.SH NAME
suspicious\-source \- search for files that are not the GPL's
"preferred form of modification"

.SH SYNOPSIS
\fBsuspicious\-source\fP

.SH DESCRIPTION
\fBsuspicious\-source\fP is a script that outputs a list of files which
are not common source files.
This should be run in the root of a source tree to find files which might
not be the "preferred form of modification" that the GPL and other licenses
require.
.PP
Neither the files inside version control system directories (like
".bzr/" or "CVS/"), nor those inside "debian/" are considered.

.SH SEE ALSO
.BR find (1)

.SH AUTHORS
\fBsuspicious\-source\fP and this manpage have been written by
Siegfried-Angel Gevatter Pujals <rainct@ubuntu.com>, based upon a
script with the same name from Martin Pitt <martin.pitt@ubuntu.com>.
.PP
Both are released under the GNU General Public License, version 3 or later.
