.TH UBUNTU_ISO "1" "June 2010" "ubuntu-dev-tools"
.SH NAME
\fBubuntu-iso\fR \- tool to examine Ubuntu CD (ISO) installation media

.SH SYNOPSIS
\fBubuntu-iso\fR <path to ISO>

.SH DESCRIPTION
When given a path to an ISO, \fBubuntu-iso\fR will determine whether it is an an Ubuntu ISO or not. If it is, it will extract and display the version information.

.SH AUTHORS
\fBubuntu-iso\fR was written by Matt Zimmerman <mdz@ubuntu.com>.

This manual page was written by Andrew Starr-Bochicchio <a.starr.b@gmail.com>.
.PP
Both are released under the terms of the GNU General Public License, version 2.
