.TH UBUNTU-BUILD "1" "June 2010" "ubuntu-dev-tools"
.SH NAME
ubuntu-build \- command-line interface to Launchpad build operations

.SH SYNOPSIS
.B ubuntu-build <srcpackage> <release> <operation>

.SH DESCRIPTION
\fBubuntu-build\fR provides a command line interface to the Launchpad build
operations.

.SH OPERATIONS
Listed below are the available operations for \fBubuntu-build\fR:
.TP
.B status
Outputs the build status of the package on Launchpad on all architectures.
.TP
.B retry
Requests that the package has another attempt at rebuilding from source.
This will only work if the package has \fIFailed to build\fR on Launchpad.
.TP
.B rescore
Requests that the package's build priority be raised in the build queue.
Only members of the Launchpad build administrators may issue this operation,
and it may only be performed on packages which \fINeed building\fR.

.SH OPTIONS
Listed below are the command line options for \fBubuntu-build\fR:
.TP
.B \-h or \-\-help
Display a help message and exit.
.TP
Retry and rescore options:
.IP
These options may only be used with the 'retry' and 'rescore'
operations.
.IP
\fB\-a\fR ARCHITECTURE, \fB\-\-arch\fR=\fIARCHITECTURE\fR
Rebuild or rescore a specific architecture. Valid
architectures include: amd64, sparc, powerpc, i386,
armel, armhf, arm64, ia64, lpia, hppa.
.TP
Batch processing:
.IP
These options and parameter ordering is only available in \fB\-\-batch\fR
mode. Usage: ubuntu\-build \fB\-\-batch\fR [options] <package>...
.IP
\fB\-\-batch\fR
Enable batch mode
.IP
\fB\-\-series\fR=\fISERIES\fR
Selects the Ubuntu series to operate on (default:
current development series)
.IP
\fB\-\-retry\fR
Retry builds (give\-back).
.IP
\fB\-\-rescore\fR=\fIPRIORITY\fR
Rescore builds to <priority>.
.IP
\fB\-\-arch2\fR=\fIARCHITECTURE\fR
Affect only 'architecture' (can be used several
times). Valid architectures are: amd64, sparc,
powerpc, i386, armel, armhf, arm64, ia64, lpia, hppa.

.SH AUTHORS
\fBubuntu-build\fR was written by Martin Pitt <martin.pitt@canonical.com>, and
this manual page was written by Jonathan Patrick Davies <jpds@ubuntu.com>.
.PP
Both are released under the terms of the GNU General Public License, version 3
or (at your option) any later version.
