.TH UBUNTU-BUILD "1" "14 August 2008" "ubuntu-dev-tools"
.SH NAME
ubuntu-build \- command-line interface to Launchpad build operations

.SH SYNOPSIS
.B ubuntu-build <srcpackage> <release> <operation>
.br
.B ubuntu-build \-\-help

.SH DESCRIPTION
\fBubuntu-build\fR provides a command line interface to the Launchpad build
operations.

.PP
\fBubuntu-build\fR uses a cookie file stored at \fI~/.lpcookie.txt\fR to authenticate
to Launchpad.
This cookie is created on run from the Mozilla Firefox cookie
file at \fI~/.mozilla/*/*/cookies.sqlite\fR.

.SH OPERATIONS
Listed below are the available operations for \fBubuntu-build\fR:
.TP
.B status
Outputs the build status of the package on Launchpad on all architectures.
.TP
.B retry
Requests that the package has another attempt at rebuilding from source.
This will only work if the package has \fIFailed to build\fR on Launchpad.
.TP
.B rescore
Requests that the package's build priority be raised in the build queue.
Only members of the Launchpad build administrators may issue this operation,
and it may only be performed on packages which \fINeed building\fR.

.SH OPTIONS
Listed below are the command line options for \fBubuntu-build\fR:
.TP
.B \-h or \-\-help
Display a help message and exit.
.TP
.B \-a or \-\-architecture
Only available for \fIrescore\fR and \fIretry\fR operations only.
This will only request the rebuilding/rescoring on the specified
architecture.

.SH AUTHORS
\fBubuntu-build\fR was written by Martin Pitt <martin.pitt@canonical.com>, and
this manual page was written by Jonathan Patrick Davies <jpds@ubuntu.com>.
.PP
Both are released under the terms of the GNU General Public License, version 3
or (at your option) any later version.
