.TH UPDATE\-MAINTAINER "1" "August 04, 2008" "ubuntu-dev-tools"

.SH NAME
update\-maintainer \- change the Maintainer field in a Debian source package

.SH SYNOPSIS
.B update\-maintainer [\fB\-\-path=<PATH>\fP] [\fB\-\-section=<SECTION>\fP]

.SH DESCRIPTION
\fBupdate\-maintainer\fP updates the Maintainer field in the source of
an Ubuntu package to match the DebianMaintainerField specification.

.SH OPTIONS
.TP
\fB\-\-path=<PATH>\fP
This option allows you to specify the path to the source directory.
.TP
\fB\-\-section=<SECTION>\fP
Manually specify the section of the package. This is necessary if the
package is not yet in the archive or if you don't have an Internet
connection available when you run \fBupdate\-maintainer\fP.

.SH SEE ALSO
See https://wiki.ubuntu.com/DebianMaintainerField for more information.

.SH AUTHOR
\fBupdate-maintainer\fP has been written by Albin Tonnerre <lut1n.tne@gmail.com>
and this manual page by Siegfried-Angel Gevatter Pujals <rainct@ubuntu.com>.
.PP
Both are released under the GNU General Public License, version 2.
